// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $cards_index from "./routes/cards/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $masonry_index from "./routes/masonry/index.tsx";
import * as $CodeBlock from "./islands/CodeBlock.tsx";
import * as $ThemeToggler from "./islands/ThemeToggler.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/cards/index.tsx": $cards_index,
    "./routes/index.tsx": $index,
    "./routes/masonry/index.tsx": $masonry_index,
  },
  islands: {
    "./islands/CodeBlock.tsx": $CodeBlock,
    "./islands/ThemeToggler.tsx": $ThemeToggler,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
